### ISSUE TITLE
Database issue 

### ISSUE THREAD

**Issue by sudarshanct** [trive-digital/Revo-ProductSliderM2#6]
Hi @chombe,

When I click on create slider, following query is displaying in magento admin,

 IF(at_visibility.value_id > 0, at_visibility.value, at_visibility_default.value) AS `visibility`, `at_position`.`position` FROM `catalog_product_entity` AS `e` INNER JOIN `catalog_product_entity_int` AS `at_visibility_default` ON (`at_visibility_default`.`entity_id` = `e`.`entity_id`) AND (`at_visibility_default`.`attribute_id` = '99') AND `at_visibility_default`.`store_id` = 0 LEFT JOIN `catalog_product_entity_int` AS `at_visibility` ON (`at_visibility`.`entity_id` = `e`.`entity_id`) AND (`at_visibility`.`attribute_id` = '99') AND (`at_visibility`.`store_id` = 1) LEFT JOIN `trive_revo_products` AS `at_position` ON (at_position.`product_id`=e.entity_id) AND (slider_id=0) WHERE (IF(at_visibility.value_id > 0, at_visibility.value, at_visibility_default.value) IN(2, 4)) ORDER BY `e`.`entity_id` ASC LIMIT 20 

while adding slider following error encountered,

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.trive_revo' doesn't exist, query was: DESCRIBE `trive_revo`
Error occurred during slider saving.

please suggest me solution.

**Comment by chombe** [comment]
hi @sudarshanct 

it looks like the extension is not installed properly.
Please check for trive_revo table in yours installation database.

**Comment by sudarshanct** [comment]
@chombe, There is no trive_revo table in database

**Comment by chombe** [comment]
@sudarshanct  we do not provide this kind of support but
you can try the following (**we are not responsible for any troubles that may come up**)

1. delete Trive_Revo record in the setup_module table
2. in the Magento root run php bin/magento setup:upgrade 
3. in the Magento root run php bin/magento setup:static-content:deploy

**Comment by sudarshanct** [comment]
@chombe, Its working, Thank you..
